### ISSUE TITLE
Library seems only partly functional when installed via npm

### ISSUE THREAD

**Issue by MattSidor** [mdesjardins/react-a11y-select#18]
Ach, sorry to be on here again with another npm-related issue...

When I install the library via `$ npm install react-a11y-select` and then `import { Select, Option } from "react-a11y-select"`, it seems to render correctly in the DOM, but `onChange` doesn't do anything and the `initialValue` attribute isn't recognized.

Same problem if I import directly from my `node_modules` path: `import { Select, Option } from "../../../../../node_modules/react-a11y-select"`

However, if I copy and paste the whole library to somewhere inside the `/src` folder of my react app, and I import from that specific folder (without any modification to my own component's code), everything works as expected.

I'm not sure why this is happening!! Seems so strange. 

I'm using [create-react-app](https://github.com/facebook/create-react-app) by the way, if that's relevant to this problem. I'm a webpack n00b, so I'm not sure if this is related to whatever webpack configuration that project uses.

I'm going to look into it...

**Comment by mdesjardins** [comment]
Wow, that's pretty strange... I wonder if there's something wrong with the dependencies??
unfortunately I'm super swamped at the moment but I can probably take a peek early next week?

**Comment by mdesjardins** [comment]
@MattSidor Sorry for the delay! I was just able to reproduce this, no ETA on a fix yet. :/

**Comment by mdesjardins** [comment]
OK, I think this is fixed now. Was a bad build/publish to NPM. 🤦‍♂️

**Comment by MattSidor** [comment]
Thanks for fixing this @mdesjardins! I've confirmed it's working now on my machine.
